### ISSUE TITLE
HMR by updating depending files is not working

### ISSUE THREAD

**Issue by hmsk** [hmsk/vite-plugin-elm#3]

**Comment by marc136** [comment]
The problem seems to be that the `transform` handler in this plugin is not executed for Elm files that were not successfully compiled.

Instead a full page refresh is triggered.

I am writing a custom handler for hot updates (see [docs](https://vitejs.dev/guide/api-plugin#handlehotupdate)) to detect whenever an imported Elm file was changed and trying to fix this issue.

**Comment by hmsk** [comment]
confirmed e10a977 solves the problem completely.
